core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('type_test.urls')),
]

type_test/urls.py
from django.urls import path
from . import views

app_name = 'type_test'

urlpatterns = [
    path('', views.index, name='home'),
    path('api/get-test', views.get_test, name='get-test'),
    path('api/parse-last-10', views.parse_last_10_tests, name='parse-last-10'),
    path('api/post-score', views.post_score, name='post-score'),
    path('sign-in', views.sign_in, name='sign-in'),
    path('sign-out', views.sign_out, name='sign-out'),
    path('sign-up', views.sign_up, name='sign-up'),
]

type_test/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    image = models.ImageField(null=True, blank=True, upload_to='profile/images')
    avg_speed = models.DecimalField(decimal_places=2, max_digits=5, default=0.00)
    avg_accuracy = models.DecimalField(decimal_places=2, max_digits=5, default=0.00)
    match_played = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    

class Test(models.Model):
    name = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    added_by = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    text_field = models.TextField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    

class CompletedTest(models.Model):
    played_by = models.ForeignKey(Profile, on_delete=models.CASCADE)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    speed = models.DecimalField(decimal_places=2, max_digits=5, default=0.00)
    accuracy = models.DecimalField(decimal_places=2, max_digits=5, default=0.00)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Completed Tests'
        ordering = ['-id']

type_test/forms.py
from django import forms
from django.contrib.auth import  password_validation


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    image = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))
    error_messages = {
        "password_mismatch": ("The two password fields didn’t match."),
    }
    password1 = forms.CharField(
        label=("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class': 'form-control', 'placeholder': 'Password'}),
        # help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=("Password confirmation"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class': 'form-control', 'placeholder': 'Password'}),
        strip=False,
        # help_text=("Enter the same password as before, for verification."),
    )

type_test/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.http.response import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import  password_validation

from .models import Test, CompletedTest, Profile
from .forms import SignUpForm

import random
import json
from decimal import Decimal


def index(request):
    return render(request, 'type_test/index.html')


# api to get new tesst 
def get_test(request):
    if request.method == 'POST' or request.method == "GET":
        tests_count = Test.objects.count()
        while True:
            try:
                test = Test.objects.get(id=random.randint(1, tests_count))
                break
            except:
                pass

        
        context = {
            'name': test.name,
            'text_field': test.text_field,
            'test_id': test.id
        }

        # checking if there is an author of a quote
        if test.author:
            context['author'] = test.author
        return JsonResponse(context, safe=False)
    return JsonResponse('Sorry', safe=False)


@login_required(login_url = 'type_test:sign-in')
def parse_last_10_tests(request):
    # checking whether the user is authenticated and have a profile or not
    context = {}
    if request.user.is_authenticated:
        try:
            profile = request.user.profile
            latest_10 = CompletedTest.objects.filter(played_by=profile)[:10]
            latest_10_accuracy = []
            latest_10_speed = []
            for i in latest_10:
                latest_10_accuracy.append(float(i.accuracy))
                latest_10_speed.append(float(i.speed))
            context['accuracy_list'] = latest_10_accuracy
            context['speed_list'] = latest_10_speed
            print(latest_10_accuracy, latest_10_speed)

            return JsonResponse(context, safe=False)

        except:
            print('no profile for user')

    return JsonResponse('User has no profile', safe=False)


# api for posting scores after completing typing test
@login_required(login_url = 'type_test:sign-in')
def post_score(request):
    if not request.user.is_authenticated:
        return JsonResponse('user not logged in :)', safe=False)

    try:
        played_by = Profile.objects.get(user=request.user)
    except:
        return JsonResponse('User has no type test profile :)', safe=False)

    if request.method == 'POST':
        body = request.body
        body = json.loads(body)

        # request body must have speed, accuracy and test_id
        if body['speed'] != None and body['accuracy'] != None:
            # played_by = request.user.profile
            played_by.match_played += 1
            played_by.avg_speed = (played_by.avg_speed * (played_by.match_played-1) + Decimal(body['speed'])) / played_by.match_played
            played_by.avg_accuracy = (played_by.avg_accuracy * (played_by.match_played-1) + Decimal(body['accuracy'])) / played_by.match_played
            played_by.save()
            test = body['test_id']
            test = Test.objects.get(id=test)
            speed = body['speed']
            accuracy = body['accuracy']
            print(played_by, test, speed, accuracy)
            CompletedTest.objects.create(played_by=played_by, test=test, speed=speed, accuracy=accuracy)
        return JsonResponse('ok posted successfully :)', safe=False)

    
# sign up view
def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST, request.FILES or None)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            name = form.cleaned_data.get('name')
            email = form.cleaned_data.get('email')
            image = form.files.get('image')
            password1 = form.cleaned_data.get('password1')
            password2 = form.cleaned_data.get('password2')
            if password1 != password2:
                # return HttpResponse('passwords do not match')
                messages.error(request, 'passwords do not match')
                return render(request, 'type_test/signup.html', {'form':form})
            try:
                password_validation.validate_password(password1)
            except:
                # return HttpResponse('password is too weak')
                messages.error(request, 'password is too weak')
                return render(request, 'type_test/signup.html', {'form':form})

            try:
                user = User.objects.create_user(username=username, email=email, password=password1)
            except:
                # return HttpResponse('username already exists')
                messages.error(request, 'username already exists')
                return render(request, 'type_test/signup.html', {'form':form})
            user.save()

            profile = Profile.objects.create(user=user, name=name, email=email, image=image)

            if user != None:
                login(request, user)
                return redirect('type_test:home')
            return HttpResponse('signed up')
    
    form = SignUpForm()
    return render(request, 'type_test/signup.html', {'form':form})


# log in view
def sign_in(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user != None:
                login(request, user)
                return redirect('type_test:home')
            return HttpResponse('signed in')

    form = AuthenticationForm()
    return render(request, 'type_test/login.html', {'form':form})


# log out
def sign_out(request):
    logout(request)
    return redirect('type_test:home')

type_test/templates/type_test/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TypeTest</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand ms-5 fs-1 fw-bolder" href="{% url 'type_test:home' %}">TypeTest</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active fs-4 fw-bold" aria-current="page" href="#">Typing Practice</a>
              </li>
              <li class="nav-item">
                <a class="nav-link fs-4 fw-bold" href="#">Quotes</a>
              </li>
            </ul>
            <ul class="navbar-nav mb-2 mx-auto mb-lg-0">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link fs-4 fw-bold" href="#">{{request.user}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fs-4 fw-bold" href="{% url 'type_test:sign-out' %}">Log Out</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link fs-4 fw-bold" href="{% url 'type_test:sign-in' %}">Log In</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link fs-4 fw-bold" href="{% url 'type_test:sign-up' %}">Sign Up</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}
    
    {% block script %}
    {% endblock script%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

type_test/templates/type_test/index.html
{% extends 'type_test/base.html' %}
{% load static %}
{% block content %}

    
    {% if request.user.is_authenticated %}
        <div class="authenticated" hidden></div>
    {% endif %}
    
    <div class="container my-4">
        <div class="row border">
            <div class="my-container row col-10">
                <div class="mx-auto fw-bold fs-100 col-12 mb-3">
                    <h2><span class="test-name"></span><span class="added-by"></span></h2>
                    <hr>
                </div>
        
                <div class="speed-counter-div col-6"><h5 class="fw-bold">Speed: <span class="speed-counter-span">0.00 </span>WPM</h5></div>
        
                <div class="accuracy-counter-div col-6"><h5 class="fw-bold">Accuracy: <span class="accuracy-counter-span">0.00</span>%</h5></div>
        
                <div class="test-container col-12">
                    
                </div>
        
                <div class="type my-3">
                    <form action="">
                        <input class="typing" type="text" name="" id="" autofocus>
                    </form>
                </div>
            </div>
    
            <div class="side-bar-result col-2 border my-2 py-5">
                Average of last 10 games <hr> <br><br>
                <h6><b>Avg. Speed: <span class="avg-speed">0.00 wpm</span></b></h6>
                <h6><b>Avg. Accuracy: <span class="avg-accuracy">0.00%</span></b></h6>
            </div>
        </div>
    </div>


    <div class="result">
        <h4>Well done. You typing speed is <span class="wpm"></span> wpm. Your accuracy is <span class="accuracy"></span>%</h4>
    </div>

{% endblock content%}

{% block script %}
    <script src="{% static 'js/type_test_main.js' %}"></script>
{% endblock script %}

type_test/templates/type_test/login.html
{% extends 'type_test/base.html' %}

{% block content %}
    <div class="container my-5">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Log In">
        </form>
    </div>
{% endblock content %}

type_test/templates/type_test/signup.html
{% extends 'type_test/base.html' %}

{% block content %}
    <div class="container my-5">
        {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                <strong>Message: </strong> {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Sign Up">
        </form>
    </div>
{% endblock content %}